### ISSUE TITLE
SEED orientation codes

### ISSUE THREAD

**Issue by WayneCrawford** [larean/obsinfo#1]
We discussed moving the orientation_code from the `sensor` level to the instrument `level`.

Currently the possible `orientation_code` s and their corresponding azimuth and dip are defined at the `sensor` level, then the `orientation_code` corresponding to a particular DAS channel is specified at the `instrument` level.  This was done because different sensors have different polarities (whether a positive voltage means an up(down) motion (seismometer/geophone) or a compressional/dilatational pressure (hydrophone/DPG)).  These affect the resulting dip value.  Here are the rules:

Instrument type       | positive voltage corresponds to |  dip to assign
----------------------|---------------------------------|--------------
Seismometer/geophone  |      upward motion              |    -90
Hydrophone/DPG        | compression (pressure increase) |   -90
Seismometer/geophone  |      downward motion            |     90
Hydrophone/DPG        | dilatation (pressure decrease)  |    90

(the pressure gauge dips are valid for UPgoing waves, but these are generally the first arrivals...)

I therefore wanted the dips (and azimuths) defined at the sensor level, rather than the (seemingly) more logical instrument level.  But in fact this isn't a great idea, because the datalogger can have a voltage inverter that changes the sense of things (this is the case for the Sercel micrOBS, for example).

We therefore decided to 
1. move the orientation code specification and correponding dip/azimuth definitions up to the instrument level.
2. add a `polarity` field to the sensor level.  The value should be "+" if an upward motion or a pressure increase results in a positive voltage, and "-" otherwise.

I also think we should add a `polarity` field to the analog_filter and datalogger levels such that a '+' means:
  - a non-inverting analog_filter
  - a datalogger whose counts increase when the input voltage increases

If the polarity is unknown, the `polarity` could be set to `None`

`obspy` could use the combined polarity of the components  to confirm the instrument-specified dip (error message if not).

The polarities of instruments existing in the database are:
Sensor | `polarity`
--------|-----------
HITECH_HTI90U (serial number prefix=220) | '-'
HITECH_HTI04-PLC-ULF | unknown
NANOMETRICS T240 and TCOMPACT | '+'
SERCEL L22 and L28 | '-'
DPG | unknown

In general, seismometers have '+' polarity, geophones have '-' polarity.  Hydrophones appear to be variable: when I contacted HiTech about their HTI90U hydrophones they responded with respect to the first three digits of the serial number!

**Comment by larean** [comment]
Implemented
