### ISSUE TITLE
Explain JSON reference on tutorial page one

### ISSUE THREAD

**Issue by WayneCrawford** [larean/obsinfo#4]
I think it would be useful to explain JSON references (and their "anchors") on the same page as you explain yaml_anchors, for two reasons:

1. It would help avoid confusion over the two different types of anchors
2. It would help avoid confusion over the different behaviors of these two "data injection" methods

The most (only?) significant difference being that JSON references replace everything that is on the same level, whereas YAML anchors only replace fields with the same name that are specified ABOVE the anchor.

**Comment by larean** [comment]
Solved
