### ISSUE TITLE
Erreurs en tutorial

### ISSUE THREAD

**Issue by WayneCrawford** [larean/obsinfo#5]
**Describe the bug**
Quelques petites erreurs dans le tutorial

In [the network section of the tutorial](https://github.com/larean/obsinfo/wiki/Tutorial---Section-III)
you wrote network-yaml instead of network.yaml

![Screenshot 2021-06-07 at 10 04 28](https://user-images.githubusercontent.com/3601379/120986431-de09fa00-c77c-11eb-9263-b2804fe30c2e.png)

In [the instrumentation subsection](https://github.com/larean/obsinfo/wiki/Tutorial---Section-III#instrumentation)

you write "Note the lonely dash...", but there isn't one anymore because you changed "instrumentations" to "instrumentation" (by the way, is it still possible to use "instrumentations"?  We probably don't need it for OBSs, but it could be useful if other, land-based groups decide to use obsinfo)

![Screenshot 2021-06-07 at 10 05 53](https://user-images.githubusercontent.com/3601379/120986481-f2e68d80-c77c-11eb-89e0-043dded358dd.png)

**Comment by larean** [comment]
Closed
